import { Geist, Geist_Mono } from "next/font/google";
import { CartProvider } from "../context/CartContext";
import Header from "../components/Header";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
     <html lang="pt-br">
        <body className="bg-[#2C1B12] text-white">
        <CartProvider>
          <Header />
          <div className="pt-26 pb   "> {/* espaço por causa do cabeçalho fixo */}
            {children}
          </div>
   
        </CartProvider>
      </body>
    </html>
  );
}
